trigger:
  branches:
    include:
      - master
      - staging
      - development

pr:
  branches:
    include:
      - master
      - staging
      - development
      - feature_*
stages:
- stage: Compile
  jobs:
    - job: Compile
      displayName: Build and Test
     # container: <Probably a gradle container here>
      steps:

      # Prepare SonarCloud Analysis
      - task: SonarCloudPrepare@1
        inputs:
          SonarCloud: 'sonar-cloud'
          organization: '2105-may24-devops'
          scannerMode: 'MSBuild'
          projectKey: '2105-may24-devops_anthony-cognizant-lab'
          projectName: 'anthony-cognizant-lab'

      # Build and Test application

      - script: chmod +x gradlew && ./gradlew build jacocoTestReport
      
      - task: SonarCloudAnalyze@1
      
      - task: SonarCloudPublish@1
        inputs:
          pollingTimeoutSec: '300'

  # - stage: DockerBuildPush
  #   jobs:
  #   - job: DockerBuildPush
  #     steps:
  #     - script: |
  #         echo "Docker Build"
  #         echo "Docker Push"