trigger:
  branches:
    include:
      - master
      - staging
      - development

pr:
  branches:
    include:
      - master
      - staging
      - development
      - feature_*

variables:
  - group: analysis-group

stages:
- stage: Compile
  pool:
      vmImage: 'ubuntu-latest'
  jobs:
    - job: Compile
      displayName: Build and Test
      steps:

      # Prepare SonarCloud Analysis
      - task: SonarCloudPrepare@1
        inputs:
          SonarCloud: 'sonar-cloud'
          organization: '2105-may24-devops'
          scannerMode: 'CLI'
          configMode: 'manual'
          cliProjectKey: '$(sonarProjectKey)'
          cliSources: '.'
          extraProperties: './build/intermediates/classes/'
          
      - task: Gradle@2
        inputs:
          gradleWrapperFile: 'gradlew'
          tasks: 'build'
          publishJUnitResults: true
          testResultsFiles: '**/TEST-*.xml'
          javaHomeOption: 'JDKVersion'
          sonarQubeRunAnalysis: true
          sqGradlePluginVersionChoice: 'build'
          spotBugsAnalysis: false
      # Build and Test application

      # - script: chmod +x gradlew && ./gradlew build jacocoTestReport

      
      # - script: ls 
      # - task: SonarCloudAnalyze@1
      
      # - task: SonarCloudPublish@1
      #   inputs:
      #     pollingTimeoutSec: '300'

  # - stage: DockerBuildPush
  #   jobs:
  #   - job: DockerBuildPush
  #     steps:
  #     - script: |
  #         echo "Docker Build"
  #         echo "Docker Push"